services:
  redis:
    image: redis:6.0
    ports:
      - '6379:6379'
  mysql:
    image: ghcr.io/serlo/serlo-mysql-database:latest
    platform: linux/x86_64
    pull_policy: always
    ports:
      - '3306:3306'
