services:
  redis:
    image: redis:6.0
    ports:
      - '6379:6379'
  mysql:
    image: eu.gcr.io/serlo-shared/serlo-mysql-database:prerelease-merge-course-pages-into-courses.2
    platform: linux/x86_64
    pull_policy: always
    ports:
      - '3306:3306'
  database-layer:
    image: eu.gcr.io/serlo-shared/serlo-org-database-layer:latest
    pull_policy: always
    ports:
      - '8080:8080'
    environment:
      - DATABASE_MAX_CONNECTIONS=5
      - DATABASE_URL=mysql://root:secret@mysql:3306/serlo
      - ENV=development
