dsn: postgres://serlo:secret@postgres:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4

serve:
  public:
    base_url: https://kratos.serlo.org
    request_log:
      disable_for_health: true
  admin:
    request_log:
      disable_for_health: true

selfservice:
  default_browser_return_url: https://serlo.org/
  allowed_return_urls:
    # TODO: try with wildcard later
    - https://fr.serlo.org/
    - https://hi.serlo.org/
    - https://de.serlo.org/
    - https://ta.serlo.org/
    - https://en.serlo.org/
    - https://es.serlo.org/
  methods:
    password:
      enabled: true
      config:
        haveibeenpwned_enabled: false
    link:
      enabled: true
      config:
        base_url: https://serlo.org/api/.ory/
    oidc:
      enabled: true
      config:
        base_redirect_uri: https://serlo.org/api/.ory/
        providers:
          - id: nbp
            provider: generic
            client_id: PLACEHOLDER
            client_secret: PLACEHOLDER
            issuer_url: https://aai.demo.meinbildungsraum.de/realms/nbp-aai
            mapper_url: file:///etc/config/kratos/user_mapper.jsonnet
          - id: vidis
            provider: generic
            client_id: PLACEHOLDER
            client_secret: PLACEHOLDER
            issuer_url: http://PLACEHOLDER
            mapper_url: file:///etc/config/kratos/vidis_user_mapper.jsonnet

  flows:
    error:
      ui_url: https://serlo.org/auth/error

    settings:
      ui_url: https://serlo.org/auth/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      use: link
      ui_url: https://serlo.org/auth/recovery

    verification:
      enabled: true
      use: link
      ui_url: https://serlo.org/auth/verification

    logout:
      after:
        default_browser_return_url: https://serlo.org/auth/login

    login:
      ui_url: https://serlo.org/auth/login
      lifespan: 10m
      after:
        password:
          hooks:
            - hook: require_verified_address
            - hook: web_hook
              config:
                url: https://api.serlo.org/kratos/updateLastLogin
                method: POST
                body: file:///etc/config/kratos/identity_id.jsonnet
                response:
                  ignore: true
        oidc:
          default_browser_return_url: https://serlo.org/auth/login

    registration:
      enable_legacy_one_step: true
      lifespan: 10m
      ui_url: https://serlo.org/auth/registration
      after:
        hooks:
          - hook: web_hook
            config:
              url: https://api.serlo.org/kratos/register
              method: POST
              body: file:///etc/config/kratos/identity_id.jsonnet
              auth:
                type: api_key
                config:
                  name: x-kratos-key
                  value: PLACEHOLDER
                  in: header
          - hook: web_hook
            config:
              url: https://PLACEHOLDER
              method: POST
              body: file:///etc/config/kratos/subscribe_newsletter_mapper.jsonnet
              can_interrupt: false
              response:
                ignore: true
              auth:
                type: basic_auth
                config:
                  user: serlo
                  password: PLACEHOLDER
        oidc:
          default_browser_return_url: https://serlo.org/auth/login
          hooks:
            - hook: web_hook
              config:
                url: https://api.serlo.org/kratos/register
                method: POST
                body: file:///etc/config/kratos/identity_id.jsonnet
                auth:
                  type: api_key
                  config:
                    name: x-kratos-key
                    value: PLACEHOLDER
                    in: header
            - hook: session
            - hook: web_hook
              config:
                url: https://PLACEHOLDER
                method: POST
                body: file:///etc/config/kratos/subscribe_newsletter_mapper.jsonnet
                can_interrupt: false
                response:
                  ignore: true
                auth:
                  type: basic_auth
                  config:
                    user: serlo
                    password: PLACEHOLDER

session:
  lifespan: 720h

secrets:
  cookie:
    - PLACEHOLDERPLACEHOLDER

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtp://PLACEHOLDER
    from_name: Serlo
    from_address: no-reply@mail.serlo.org
  templates:
    verification:
      valid:
        email:
          subject: http://serlo.org/api/.ory/mail-templates/verification/valid/email.subject.gotmpl
          body:
            html: http://serlo.org/api/.ory/mail-templates/verification/valid/email.body.gotmpl
            plaintext: http://serlo.org/api/.ory/mail-templates/verification/valid/email.body.plaintext.gotmpl
      invalid:
        email:
          subject: http://serlo.org/api/.ory/mail-templates/verification/invalid/email.subject.gotmpl
          body:
            html: http://serlo.org/api/.ory/mail-templates/verification/invalid/email.body.gotmpl
            plaintext: http://serlo.org/api/.ory/mail-templates/verification/invalid/email.body.plaintext.gotmpl
    recovery:
      valid:
        email:
          subject: http://serlo.org/api/.ory/mail-templates/recovery/valid/email.subject.gotmpl
          body:
            html: http://serlo.org/api/.ory/mail-templates/recovery/valid/email.body.gotmpl
            plaintext: http://serlo.org/api/.ory/mail-templates/recovery/valid/email.body.plaintext.gotmpl
      invalid:
        email:
          subject: http://serlo.org/api/.ory/mail-templates/recovery/invalid/email.subject.gotmpl
          body:
            html: http://serlo.org/api/.ory/mail-templates/recovery/invalid/email.body.gotmpl
            plaintext: http://serlo.org/api/.ory/mail-templates/recovery/invalid/email.body.plaintext.gotmpl
