version: v1.0.0

dev: true

dsn: postgres://serlo:secret@postgres:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4

serve:
  public:
    base_url: http://localhost:4433/
  admin:
    base_url: http://localhost:4434/

selfservice:
  default_browser_return_url: http://localhost:3000/

  methods:
    password:
      enabled: true
      config:
        haveibeenpwned_enabled: false
        min_password_length: 6
        identifier_similarity_check_enabled: false
    link:
      enabled: true
    oidc:
      enabled: true
      config:
        providers:
          - id: nbp
            provider: generic
            client_id: serlo
            client_secret: H8t6WKWtGwFjqNfuAjqxrwCfsdznMAfj
            issuer_url: http://nbp:11111/realms/master
            mapper_url: file:///etc/config/kratos/user_mapper.jsonnet

  flows:
    error:
      ui_url: http://localhost:3000/auth/error
    logout:
      after:
        default_browser_return_url: http://localhost:3000/auth/login
    login:
      ui_url: http://localhost:3000/auth/login
      lifespan: 10m
      after:
        password:
          hooks:
            - hook: require_verified_address
            - hook: web_hook
              config:
                url: http://host.docker.internal:3001/kratos/updateLastLogin
                method: POST
                body: file:///etc/config/kratos/identity_id.jsonnet
                response:
                  ignore: true
        oidc:
          default_browser_return_url: http://localhost:3000/auth/login

    registration:
      ui_url: http://localhost:3000/auth/registration
      after:
        hooks:
          - hook: web_hook
            config:
              url: http://host.docker.internal:3001/kratos/register
              method: POST
              can_interrupt: true
              body: file:///etc/config/kratos/identity_id.jsonnet
              auth:
                type: api_key
                config:
                  name: x-kratos-key
                  value: api.serlo.org-kratos-secret
                  in: header
          - hook: web_hook
            config:
              url: https://<YOUR_DC>.api.mailchimp.com/3.0/lists/<YOUR_LIST_ID>/members
              method: POST
              body: file:///etc/config/kratos/add_to_newsletter.jsonnet
              can_interrupt: false
              response:
                ignore: true
              auth:
                type: basic_auth
                config:
                  user: serlo
                  password: PUT_HERE_YOUR_MAILCHIMP_API_KEY

        oidc:
          hooks:
            - hook: web_hook
              config:
                url: http://host.docker.internal:3001/kratos/register
                method: POST
                body: file:///etc/config/kratos/identity_id.jsonnet
                auth:
                  type: api_key
                  config:
                    name: x-kratos-key
                    value: api.serlo.org-kratos-secret
                    in: header
            - hook: web_hook
              config:
                url: https://<YOUR_DC>.api.mailchimp.com/3.0/lists/<YOUR_LIST_ID>/members
                method: POST
                body: file:///etc/config/kratos/add_to_newsletter.jsonnet
                can_interrupt: false
                response:
                  ignore: true
                auth:
                  type: basic_auth
                  config:
                    user: serlo
                    password: PUT_HERE_YOUR_MAILCHIMP_API_KEY
            - hook: session
          default_browser_return_url: http://localhost:3000/auth/login
    verification:
      enabled: true
      use: link
      ui_url: http://localhost:3000/auth/verification
    recovery:
      enabled: true
      use: link
      ui_url: http://localhost:3000/auth/recovery

    settings:
      ui_url: http://localhost:3000/auth/settings
log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:secret@mailslurper:1025/?skip_ssl_verify=true
  template_override_path: /etc/config/kratos/email-templates/
  templates:
    verification:
      valid:
        email:
          subject: http://host.docker.internal:3000/api/.ory/mail-templates/verification/valid/email.subject.gotmpl
          body:
            html: http://host.docker.internal:3000/api/.ory/mail-templates/verification/valid/email.body.gotmpl
            plaintext: http://host.docker.internal:3000/api/.ory/mail-templates/verification/valid/email.body.plaintext.gotmpl
      invalid:
        email:
          subject: http://host.docker.internal:3000/api/.ory/mail-templates/verification/invalid/email.subject.gotmpl
          body:
            html: http://host.docker.internal:3000/api/.ory/mail-templates/verification/invalid/email.body.gotmpl
            plaintext: http://host.docker.internal:3000/api/.ory/mail-templates/verification/invalid/email.body.plaintext.gotmpl
    recovery:
      valid:
        email:
          subject: http://host.docker.internal:3000/api/.ory/mail-templates/recovery/valid/email.subject.gotmpl
          body:
            html: http://host.docker.internal:3000/api/.ory/mail-templates/recovery/valid/email.body.gotmpl
            plaintext: http://host.docker.internal:3000/api/.ory/mail-templates/recovery/valid/email.body.plaintext.gotmpl
      invalid:
        email:
          subject: http://host.docker.internal:3000/api/.ory/mail-templates/recovery/invalid/email.subject.gotmpl
          body:
            html: http://host.docker.internal:3000/api/.ory/mail-templates/recovery/invalid/email.body.gotmpl
            plaintext: http://host.docker.internal:3000/api/.ory/mail-templates/recovery/invalid/email.body.plaintext.gotmpl
