name: CI Checks

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-node
        with:
          install: false
      - run: yarn npm audit

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-node
      - run: yarn lint:eslint

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-node
      - run: yarn lint:prettier

  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-node
      - run: yarn lint:tsc

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-mysql
      - uses: ./.github/actions/setup-node
      - run: yarn start:containers
      - run: scripts/mysql/wait-for-mysql.sh
      - run: yarn migrate:all
      # It seems that running tests for changing taxonomies in parallel
      # to metadata query messes up with internal optimizatons so that
      # testing metadata endpoint runs into a timout
      # => solution: Run tests for metadata in an extra step
      - run: yarn test metadata.ts
      - run: yarn test --testPathIgnorePatterns metadata.ts __utils__

  codegen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-node
      - run: yarn codegen
      - name: Check for uncommitted changes
        run: |
          if ! git diff --exit-code; then
            echo "There are uncommitted changes in the repository."
            exit 1
          fi
