name: Pacts
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 18.x
      - run: yarn --immutable --immutable-cache
      - run: yarn start:redis
      - run: yarn pacts
